version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/latest/download/aws-iam-authenticator-linux-amd64
      - chmod +x aws-iam-authenticator
      - mv aws-iam-authenticator /usr/local/bin/
  pre_build:
    commands:
      - echo "Configuring AWS credentials..."
      - aws configure set aws_access_key_id AKIAQ5TETDUNKPVMHVFO
      - aws configure set aws_secret_access_key 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
      - aws configure set default.region us-east-1ß
      - echo "Setting up kubeconfig..."
      - aws eks update-kubeconfig --name eksctl-udacity-kuber --region us-east-1
  build:
    commands:
      - echo "Deploying PostgreSQL..."
      - kubectl apply -f postgres-deployment.yml
      - echo "Deploying application..."
      - kubectl apply -f udacity-final-project-deployment.yaml
  post_build:
    commands:
      - echo "Deployment completed."
