version: '3.8'

services:
  web:
    build: .
    ports:
      - "5050:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/casting_agency"
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0"

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d casting_agency"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres_data: