apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-final-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-final-project
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: udacity-final-project
    spec:
      containers:
      - name: udacity-final-project
        image: kubergoel477/udacity-final-project:latest
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/casting_agency"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: udacity-final-project-service
spec:
  selector:
    app: udacity-final-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
