"""empty message

Revision ID: 39aeea4fda28
Revises: 9dc3a01f7b4c
Create Date: 2025-01-17 00:56:27.547554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39aeea4fda28'
down_revision = '9dc3a01f7b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casting_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casting_role', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
