"""empty message

Revision ID: 7daff2a4caab
Revises: 39aeea4fda28
Create Date: 2025-01-19 14:51:37.134259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7daff2a4caab'
down_revision = '39aeea4fda28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casting_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_updated_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casting_role', schema=None) as batch_op:
        batch_op.drop_column('last_updated_time')
        batch_op.drop_column('creation_time')

    # ### end Alembic commands ###
